# Generated by Django 3.2.4 on 2021-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(max_length=255, null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('height', models.CharField(max_length=255, null=True)),
                ('wight', models.CharField(max_length=255, null=True)),
                ('hip_circumference', models.CharField(max_length=255, null=True)),
                ('waist', models.CharField(max_length=255, null=True)),
                ('wrist_circumference', models.CharField(max_length=255, null=True)),
                ('blood_pressure', models.CharField(max_length=255, null=True)),
                ('heart_rate_variability', models.CharField(max_length=255, null=True)),
                ('heart_rate_alone', models.CharField(max_length=255, null=True)),
                ('vo2max', models.CharField(max_length=255, null=True)),
                ('body_temparature', models.CharField(max_length=255, null=True)),
                ('common_diseases', models.CharField(max_length=255, null=True)),
                ('blood_glucose_level', models.CharField(max_length=255, null=True)),
                ('movement_sleep_pattern', models.CharField(max_length=255, null=True)),
                ('libido', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
