# Generated by Django 3.2.4 on 2021-10-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_amt', models.CharField(max_length=255, null=True)),
                ('p_type', models.CharField(max_length=255, null=True)),
                ('userid', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
