# Generated by Django 3.2.4 on 2021-10-10 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_auto_20211010_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bio_Pathologiest',
        ),
    ]
