from django.db import models

class Biodata(models.Model):
	userid = models.CharField(max_length=255, null=True)
	sex = models.CharField(max_length=255, null=True)
	nationality = models.CharField(max_length=255, null=True)
	height = models.CharField(max_length=255, null=True)
	weight = models.CharField(max_length=255, null=True)
	hip_circumference = models.CharField(max_length=255, null=True)
	waist = models.CharField(max_length=255, null=True)
	wrist_circumference = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	heart_rate_variability = models.CharField(max_length=255, null=True)
	heart_rate_alone = models.CharField(max_length=255, null=True)
	vo2max = models.CharField(max_length=255, null=True)
	body_temparature = models.CharField(max_length=255, null=True)
	common_diseases = models.CharField(max_length=255, null=True)
	blood_glucose_level = models.CharField(max_length=255, null=True)
	movement_sleep_pattern = models.CharField(max_length=255, null=True)
	libido = models.CharField(max_length=255, null=True)

	def __str__(self):
		return self.nationality
class Risks(models.Model):
	riskdes = models.TextField()

	def __str__(self):
		return self.riskdes

class Recommendaions(models.Model):
	recommdes = models.TextField()
	cost = models.CharField(max_length=255, null=True)

	def __str__(self):
		return self.recommdes

class Subscriptions(models.Model):
	pack_name = models.CharField(max_length=255, null=True)
	pack_exp = models.CharField(max_length=255, null=True)
	cost_per_recom = models.CharField(max_length=255, null=True)
	long_coin = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)

class Rewards(models.Model):
	r_amt = models.CharField(max_length=255, null=True)
	r_type = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)
	
	def __str__(self):
		return self.r_type

class Payments(models.Model):
	p_amt = models.CharField(max_length=255, null=True)
	p_type = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)

class Files(models.Model):
	file = models.FileField(blank=False, null=False)

class CSV(models.Model):
	name = models.CharField(max_length=255, null=True)
	age = models.CharField(max_length=255, null=True)



class Diabetes(models.Model):
	di_id = models.CharField(max_length=255, null=True)
	age = models.CharField(max_length=255, null=True)
	gender = models.CharField(max_length=255, null=True)
	BMI = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	cholesterol= models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	potassium= models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	sodium = models.CharField(max_length=255, null=True)
	hematocrit = models.CharField(max_length=255, null=True)
	hemoglobin = models.CharField(max_length=255, null=True)
	platelet_count = models.CharField(max_length=255, null=True)
	white_blood_cells = models.CharField(max_length=255, null=True)
	red_blood_cells = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	uric_acid = models.CharField(max_length=255, null=True)
	globulin = models.CharField(max_length=255, null=True)
	d_dimer = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class CVD(models.Model):
	di_id = models.CharField(max_length=255, null=True)
	age = models.CharField(max_length=255, null=True)
	gender = models.CharField(max_length=255, null=True)
	BMI = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	cholesterol = models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	hematocrit = models.CharField(max_length=255, null=True)
	potassium = models.CharField(max_length=255, null=True)
	hemoglobin = models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	urea_nitrogen = models.CharField(max_length=255, null=True)
	sodium = models.CharField(max_length=255, null=True)
	platelet_count = models.CharField(max_length=255, null=True)
	white_blood_cells = models.CharField(max_length=255, null=True)
	red_blood_cells = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	troponin_t = models.CharField(max_length=255, null=True)
	globulin = models.CharField(max_length=255, null=True)
	c_reactive_protein = models.CharField(max_length=255, null=True)
	d_dimer = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Stroke(models.Model):
	di_id = models.CharField(max_length=255, null=True)
	age = models.CharField(max_length=255, null=True)
	gender = models.CharField(max_length=255, null=True)
	BMI = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	cholesterol = models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	hematocrit = models.CharField(max_length=255, null=True)
	potassium = models.CharField(max_length=255, null=True)
	hematocrit = models.CharField(max_length=255, null=True)
	bicarbonate = models.CharField(max_length=255, null=True)
	urea_nitrogen = models.CharField(max_length=255, null=True)
	sodium = models.CharField(max_length=255, null=True)
	platelet_count = models.CharField(max_length=255, null=True)
	white_blood_cells = models.CharField(max_length=255, null=True)
	red_blood_cells = models.CharField(max_length=255, null=True)
	calcium = models.CharField(max_length=255, null=True)
	lymphocytes = models.CharField(max_length=255, null=True)
	neutrophils = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	troponin_t = models.CharField(max_length=255, null=True)
	globulin = models.CharField(max_length=255, null=True)
	d_dimer = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Breast_cancer(models.Model):
	di_id = models.CharField(max_length=255, null=True)
	age = models.CharField(max_length=255, null=True)
	gender = models.CharField(max_length=255, null=True)
	BMI = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	cholesterol = models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	calcium = models.CharField(max_length=255, null=True)
	CA_15_3 = models.CharField(max_length=255, null=True)
	СА_125 = models.CharField(max_length=255, null=True)
	CYFRA_21_1 = models.CharField(max_length=255, null=True)
	СА_72_4 = models.CharField(max_length=255, null=True)
	cancer_embryonic_antigen = models.CharField(max_length=255, null=True)
	potassium = models.CharField(max_length=255, null=True)
	uric_acid = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	hematocrit = models.CharField(max_length=255, null=True)
	sodium = models.CharField(max_length=255, null=True)
	hemoglobin = models.CharField(max_length=255, null=True)
	platelet_ount = models.CharField(max_length=255, null=True)
	white_blood_cells = models.CharField(max_length=255, null=True)
	red_blood_cells = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Chronic_kidney_disease(models.Model):
	di_id = models.CharField(max_length=255, null=True)
	age = models.CharField(max_length=255, null=True)
	gender = models.CharField(max_length=255, null=True)
	BMI = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	cholesterol = models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	potassium = models.CharField(max_length=255, null=True)
	uric_acid = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	hematocrit = models.CharField(max_length=255, null=True)
	sodium = models.CharField(max_length=255, null=True)
	hemoglobin = models.CharField(max_length=255, null=True)
	platelet_count = models.CharField(max_length=255, null=True)
	white_blood_cells = models.CharField(max_length=255, null=True)
	red_blood_cells = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)
	


class Coronary_artery_disease(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	Troponin_I = models.CharField(max_length=255, null=True)
	Troponin_T = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	Blood_pressure = models.CharField(max_length=255, null=True)
	Total_cholesterol = models.CharField(max_length=255, null=True)
	Fibrinogen = models.CharField(max_length=255, null=True)
	circular_RNA = models.CharField(max_length=255, null=True)
	Myoglobin = models.CharField(max_length=255, null=True)
	SGOT = models.CharField(max_length=255, null=True)
	D_dimer = models.CharField(max_length=255, null=True)
	B_type_natriuretic_peptide = models.CharField(max_length=255, null=True)
	sTNFR_1 = models.CharField(max_length=255, null=True)
	CFR = models.CharField(max_length=255, null=True)
	Phosphodiesterase_and_Pentraxin3 = models.CharField(max_length=255, null=True)
	ST2 = models.CharField(max_length=255, null=True)
	GDF_15 = models.CharField(max_length=255, null=True)
	BSFA= models.CharField(max_length=255, null=True)
	Creatine_phosphokinase = models.CharField(max_length=255, null=True)
	Lactate_dehydrogenase = models.CharField(max_length=255, null=True)
	Aminotransferase = models.CharField(max_length=255, null=True)
	Triglyceride_concentration = models.CharField(max_length=255, null=True)
	Coronary_calcium = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Alzheimers_disease(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	Aβ_protein = models.CharField(max_length=255, null=True)
	t_tau = models.CharField(max_length=255, null=True)
	p_tau = models.CharField(max_length=255, null=True)
	isoprostane_8 = models.CharField(max_length=255, null=True)
	iPF2a_VI = models.CharField(max_length=255, null=True)
	total_free_amino_acids = models.CharField(max_length=255, null=True)
	hydroxy_deoxyguanosine = models.CharField(max_length=255, null=True)
	glycine_and_enzymatic = models.CharField(max_length=255, null=True)
	S100A9_protein = models.CharField(max_length=255, null=True)
	Decreased_glucose_metabolism = models.CharField(max_length=255, null=True)
	NFL_CSF = models.CharField(max_length=255, null=True)
	Chromosome_21 = models.CharField(max_length=255, null=True)
	chromosome_14 = models.CharField(max_length=255, null=True)
	chromosome_1st = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Stroke_P(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	platelet_count = models.CharField(max_length=255, null=True)
	brain_natriuretic_peptide = models.CharField(max_length=255, null=True)
	S100B_IL6 = models.CharField(max_length=255, null=True)
	linoleic_acid = models.CharField(max_length=255, null=True)
	D_dimer = models.CharField(max_length=255, null=True)
	fibrinogen_levels = models.CharField(max_length=255, null=True)
	erythrocyte_sedimentation_rate = models.CharField(max_length=255, null=True)
	Lp_PLA2 = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	P_selectin = models.CharField(max_length=255, null=True)
	fibrinogen = models.CharField(max_length=255, null=True)
	troponin = models.CharField(max_length=255, null=True)
	glutamate = models.CharField(max_length=255, null=True)
	GFAP = models.CharField(max_length=255, null=True)
	NDKA = models.CharField(max_length=255, null=True)
	MMP_9 = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Cancer_trachea_bronchi_lungs(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	NSE = models.CharField(max_length=255, null=True)
	CEA = models.CharField(max_length=255, null=True)
	Cyfra = models.CharField(max_length=255, null=True)
	hemogloyuin_and_erythrocyte = models.CharField(max_length=255, null=True)
	sputum_analysis = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Lower_Respiratory_Tract_Infections(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	procalcitonin = models.CharField(max_length=255, null=True)
	leukocyte_level = models.CharField(max_length=255, null=True)
	neutrophil_level = models.CharField(max_length=255, null=True)
	antibodies = models.CharField(max_length=255, null=True)
	bacteria = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Colon_rectal_cancer(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	antigen_CA_19_9 = models.CharField(max_length=255, null=True)
	antigen_CA_50 = models.CharField(max_length=255, null=True)
	cancer_embryonic = models.CharField(max_length=255, null=True)
	erythrocyte_level = models.CharField(max_length=255, null=True)
	hyperplasia = models.CharField(max_length=255, null=True)
	Cytokeratin = models.CharField(max_length=255, null=True)
	sialosil_Tn = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)



class Kidney_disease(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	glomerular_filtration_rate = models.CharField(max_length=255, null=True)
	cholesterol_level = models.CharField(max_length=255, null=True)
	blood_creatinine_level = models.CharField(max_length=255, null=True)
	serum_cystatin_C = models.CharField(max_length=255, null=True)
	potassium = models.CharField(max_length=255, null=True)
	uric_acid = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	NGAL = models.CharField(max_length=255, null=True)
	interleukin_18 = models.CharField(max_length=255, null=True)
	KIM_1 = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Hypertensive_heart_disease(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	blood_pressure = models.CharField(max_length=255, null=True)
	cholesterol_level = models.CharField(max_length=255, null=True)
	uric_acid = models.CharField(max_length=255, null=True)
	fasting_glucose = models.CharField(max_length=255, null=True)
	albumin = models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	ankle_brachial = models.CharField(max_length=255, null=True)
	hemoglobin_level = models.CharField(max_length=255, null=True)
	thyroid_stimulating = models.CharField(max_length=255, null=True)
	thyroid_hormone = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Diabetes_P(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	glucose_level = models.CharField(max_length=255, null=True)
	insulin = models.CharField(max_length=255, null=True)
	cholesterol = models.CharField(max_length=255, null=True)
	glycated_hemoglobin = models.CharField(max_length=255, null=True)
	insulin = models.CharField(max_length=255, null=True)
	C_peptide = models.CharField(max_length=255, null=True)
	dihydroceramides = models.CharField(max_length=255, null=True)
	autoantibodie_decarboxylase = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	natriuretic_peptide = models.CharField(max_length=255, null=True)
	vitamin_D = models.CharField(max_length=255, null=True)
	Uric_acid = models.CharField(max_length=255, null=True)
	VOC = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)



class Chronic_obstructive_pulmonary(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	exhaled_air_condensate = models.CharField(max_length=255, null=True)
	induced_sputum = models.CharField(max_length=255, null=True)
	fibrinogen = models.CharField(max_length=255, null=True)
	IL_6_8 = models.CharField(max_length=255, null=True)
	C_reactive_protein = models.CharField(max_length=255, null=True)
	matrix_metalloproteinase = models.CharField(max_length=255, null=True)
	surfactate_protein = models.CharField(max_length=255, null=True)
	chemokine = models.CharField(max_length=255, null=True)
	cytokines = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Stomach_cancer(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	tumor_marker_CA = models.CharField(max_length=255, null=True)
	antigen_CA = models.CharField(max_length=255, null=True)
	cancer_embryonic_antigen = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Intestinal_infections(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	antibodies = models.CharField(max_length=255, null=True)
	bacteria = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Tuberculosis(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	erythrocytes = models.CharField(max_length=255, null=True)
	leukocytes = models.CharField(max_length=255, null=True)
	neutrophils = models.CharField(max_length=255, null=True)
	hemoglobin = models.CharField(max_length=255, null=True)
	cytokine = models.CharField(max_length=255, null=True)
	C_reactive = models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Cirrhosis_liver(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	hyaluronic_acid = models.CharField(max_length=255, null=True)
	collagens = models.CharField(max_length=255, null=True)
	aminoterminal = models.CharField(max_length=255, null=True)
	metalloproteinases = models.CharField(max_length=255, null=True)
	IMP = models.CharField(max_length=255, null=True)
	aminotransferases = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	platelets = models.CharField(max_length=255, null=True)
	Alkaline_Phosphatase = models.CharField(max_length=255, null=True)
	Sorbitol_dehydrogenase = models.CharField(max_length=255, null=True)
	Albumin = models.CharField(max_length=255, null=True)
	cholesterol = models.CharField(max_length=255, null=True)
	iron_level = models.CharField(max_length=255, null=True)
	blood_urea_level = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Parkinson_disease(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	oligomeric_alpha_synuclein = models.CharField(max_length=255, null=True)
	tspontaneous_apoptosis = models.CharField(max_length=255, null=True)
	genetic = models.CharField(max_length=255, null=True)
	imaging = models.CharField(max_length=255, null=True)
	D1_D2_lymphocytes = models.CharField(max_length=255, null=True)
	homovanillic_acid = models.CharField(max_length=255, null=True)
	C_reactive = models.CharField(max_length=255, null=True)
	microrna_level = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)



class HIV_AIDS(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	specific_antibodies = models.CharField(max_length=255, null=True)
	leukoplakia = models.CharField(max_length=255, null=True)
	T_lymphocyte_counts = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Malaria(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	malarial_plasmodium = models.CharField(max_length=255, null=True)
	erythrocytes = models.CharField(max_length=255, null=True)
	malaria_antibodies = models.CharField(max_length=255, null=True)
	bilirubin = models.CharField(max_length=255, null=True)
	glucose = models.CharField(max_length=255, null=True)
	urea = models.CharField(max_length=255, null=True)
	creatinine = models.CharField(max_length=255, null=True)
	albumen = models.CharField(max_length=255, null=True)
	leukocytes = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Liver_cancer(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	Alpha_fetoprotein = models.CharField(max_length=255, null=True)
	СА_199 = models.CharField(max_length=255, null=True)
	Prominin_1 = models.CharField(max_length=255, null=True)
	cytokeratin_7_9 = models.CharField(max_length=255, null=True)
	ALDH = models.CharField(max_length=255, null=True)
	CD_90 = models.CharField(max_length=255, null=True)
	CD_44 = models.CharField(max_length=255, null=True)
	CD_13 = models.CharField(max_length=255, null=True)
	EpCAM = models.CharField(max_length=255, null=True)
	Hepatic_oval_cells = models.CharField(max_length=255, null=True)
	B50_1 = models.CharField(max_length=255, null=True)
	SALL4 = models.CharField(max_length=255, null=True)
	ICAM_1 = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Hepatitis_B(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	antigen_HBsAg = models.CharField(max_length=255, null=True)
	antigen_HBc = models.CharField(max_length=255, null=True)
	antigen_HBeAg = models.CharField(max_length=255, null=True)
	antigen_HBs = models.CharField(max_length=255, null=True)
	antibodies = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)


class Meningitis(models.Model):
	name_id = models.CharField(max_length=255, null=True)
	cytokines_IL_1b = models.CharField(max_length=255, null=True)
	cytokines_IL_13 = models.CharField(max_length=255, null=True)
	cytokines_TNF = models.CharField(max_length=255, null=True)
	cytokines_GM_CSF = models.CharField(max_length=255, null=True)
	glucose_level = models.CharField(max_length=255, null=True)
	lactate_level = models.CharField(max_length=255, null=True)
	D_dimer = models.CharField(max_length=255, null=True)
	santigen_fluids = models.CharField(max_length=255, null=True)
	accuracy = models.CharField(max_length=255, null=True)
	responsible_model = models.CharField(max_length=255, null=True)
	ave_value = = models.CharField(max_length=255, null=True)
	risks = models.CharField(max_length=255, null=True)
	recommendations = models.CharField(max_length=255, null=True)
	userid = models.CharField(max_length=255, null=True)



